---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 2836771663-mf5dc8hTxZOXc6470fA7X1V2QRdkNIUWdNqeiia
:access_token_secret: AkINL4PEmKMVT2dwUz21lUih6mvaiaXFMEiOR3crcwcoc
